services:
  api:
    build: .
    container_name: travel_planner_api
    ports:
      - "8000:8000"
    environment:
      APP_NAME: ${APP_NAME}
      DEBUG: ${DEBUG}
      DATABASE_URL: ${DATABASE_URL}
      ART_INSTITUTE_API_URL: ${ART_INSTITUTE_API_URL}
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
